/**
 * Generate TypeScript types for the RPC contract.
 *
 * Reads drivers/WordDriver/schema/methods.json, emits per-method
 * `Params` and `Result` interfaces, plus a `MethodName` union and
 * `MethodMap` lookup, into packages/rpc-schema/src/methods.ts.
 *
 * Hand-written interfaces are easier to read here than running
 * json-schema-to-typescript because the shape is small and we want
 * tight control over the discriminated union.
 *
 * Run: bun run gen
 */

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { compile } from "json-schema-to-typescript";

const REPO = resolve(import.meta.dirname, "..");
const SCHEMA_PATH = resolve(REPO, "drivers/WordDriver/schema/methods.json");
const OUT_PATH = resolve(REPO, "packages/rpc-schema/src/methods.ts");

interface MethodDef {
  description: string;
  params: object;
  result: object;
}

interface SchemaFile {
  methods: Record<string, MethodDef>;
}

async function main() {
  const file = JSON.parse(readFileSync(SCHEMA_PATH, "utf-8"));
  // The methods live under properties.methods.properties.{name}.
  const methods = file?.properties?.methods?.properties as
    | Record<string, MethodDef>
    | undefined;
  if (!methods) throw new Error("schema: expected properties.methods.properties to be a map of method definitions");
  const methodNames = Object.keys(methods).sort();

  const lines: string[] = [
    "// AUTOGENERATED by scripts/gen-rpc-types.ts — do not edit by hand.",
    "// Run `bun run gen` to regenerate from drivers/WordDriver/schema/methods.json.",
    "",
  ];

  // Per-method Params / Result interfaces
  for (const name of methodNames) {
    const def = methods[name];
    const tag = tsName(name);

    const paramsTs = await compile(
      { ...def.params, title: `${tag}Params` } as any,
      `${tag}Params`,
      { bannerComment: "", additionalProperties: false }
    );
    const resultTs = await compile(
      { ...def.result, title: `${tag}Result` } as any,
      `${tag}Result`,
      { bannerComment: "", additionalProperties: false }
    );

    lines.push(`// ${name} — ${def.description}`);
    lines.push(paramsTs.trim());
    lines.push(resultTs.trim());
    lines.push("");
  }

  // Method name union
  lines.push(
    `export type MethodName = ${methodNames.map((n) => JSON.stringify(n)).join(" | ")};`,
    ""
  );

  // Lookup maps
  lines.push("export interface MethodParams {");
  for (const name of methodNames) {
    lines.push(`  ${JSON.stringify(name)}: ${tsName(name)}Params;`);
  }
  lines.push("}");
  lines.push("");

  lines.push("export interface MethodResults {");
  for (const name of methodNames) {
    lines.push(`  ${JSON.stringify(name)}: ${tsName(name)}Result;`);
  }
  lines.push("}");
  lines.push("");

  lines.push(
    "export type Params<M extends MethodName> = MethodParams[M];",
    "export type Result<M extends MethodName> = MethodResults[M];",
    "",
    "export interface RpcRequest<M extends MethodName = MethodName> {",
    "  id: string;",
    "  method: M;",
    "  params: Params<M>;",
    "}",
    "",
    "export interface RpcResponse<M extends MethodName = MethodName> {",
    "  id: string | null;",
    "  result: Result<M> | null;",
    "  error: string | null;",
    "}",
    ""
  );

  const out = lines.join("\n");
  mkdirSync(dirname(OUT_PATH), { recursive: true });
  writeFileSync(OUT_PATH, out, "utf-8");
  console.log(`Wrote ${OUT_PATH} (${methodNames.length} methods)`);
}

/**
 * Convert "polish.replaceRange" -> "PolishReplaceRange" so we can build
 * legal TS identifiers.
 */
function tsName(method: string): string {
  return method
    .split(/[._-]/)
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join("");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
